apiVersion: v1
kind: Secret
metadata:
  name: wikibase
  namespace: wikibase
type: Opaque
data:
  db.user: d2lraXVzZXI=
  db.name: bXlfd2lraQ==
  db.pass: c3FscGFzcw==
  db.server: bWVkaWF3aWtpLW15c3FsLndpa2liYXNlOjMzMDY=
  mw.admin.name: YWRtaW4=
  mw.admin.pass: YWRtaW5wYXNz
  mw.admin.email: YWRtaW5AZXhhbXBsZS5jb20=
  mw.wg.secret.key: c2VjcmV0a2V5
  oauth.consumer.key: NTU5ZmNmMWRhMTUzYzVlYzRiMmZiZWZhN2MzYzM5NWI=
  oauth.consumer.secret: NTdjYWQzM2RhMDAxNWRjZTFlOTRhNTk3OTA4ZTE5ODQ4NzE0YTZhZg==
